apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-development"
  labels:
    app: "mongo-development"
spec:
  ports:
    - 
      name: "mongodb"
      port: 27017
      targetPort: 27017
  clusterIP: "None"
  selector:
    app: "mongo-development"
